### ISSUE TITLE
Make Alexa start listening via service call

### ISSUE THREAD

**Issue by eldotta** [custom-components/alexa_media_player#1022]
I hope I didn't miss this feature in the docs... thank you for a hint, if I did! :)

**Is your feature request related to a problem? Please describe.**
I have some use cases in which Alexa asks for confirmation before a script/automation proceeds.

For example, when I set an alarm in the bedroom, Alexa asks if the lights should be switched off. 

I added two routines to Alexa ("yes please" and "no thanks") which trigger respective dummy scripts in Home Assistant to realize this. The script/automation includes a wait_template tied to the respective dummy script. 

This works totally fine, but of course I have to say "Alexa" each time to make the Echo listening again before I can answer. 

**Describe the solution you'd like**
I'd like to make Alexa listening after asking a question via some service call. 

**Describe alternatives you've considered**
I tried the "follow-up mode", but as you can imagine this is very limited and only works if I triggered Alexa to listen before. 

I don't wanna go for custom skill.

**Additional context**
Besides "no" and "yes" answers, this concept could be extended to answering with numbers via a "light dummy".

**Comment by alandtse** [comment]
I'm not sure I understand the feature request, but you're not talking about this right? https://community.home-assistant.io/t/actionable-notifications-via-alexa-media-player/193992

If not, we are limited to what the app can do so is this available in the app?

**Comment by eldotta** [comment]
Oh, yes, basically that's the same use case, but with a custom skill. 

Here's a code snippet of the automation example I mentioned. What I would like is a service that makes the Echo listen for a command the same way saying "Alexa" or pushing the action button on the device does. Then I could call this service after the "alexa_tts" script to answer directly without saying "Alexa" again. Hope I could make myself clear now. The "alexa_tts" script is just a wrapper for the notification service btw.

Since you can make the app listen for commands it's more or less available in the app, but I suppose what I want will not be possible, since I can't make other Echo devices listen for commands via the app, right?

```
- id: alexa_alarm_turn_off_lights
  alias: alexa_alarm_turn_off_lights
  trigger:
  - platform: template
    value_template: '{{ states.sensor.dot_bedroom_next_alarm.state != "unavailable" }}'
  action:
  - service: script.alexa_tts
    data:
      message: 'Do you want me to switch off the lights?'
  - wait_template: '{{ states.script.alexa_understood_yes.state == "on" or states.script.alexa_understood_no.state == "on" }}'
    timeout: '00:01:00'
    continue_on_timeout: true
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ states.script.alexa_understood_yes.state == "on" }}'
      sequence:
        - service: light.turn_off
          entity_id: light.hue_apartment
```
