### ISSUE TITLE
Is a new service: notify.alexa_media_last_alexa possible?

### ISSUE THREAD

**Issue by danielbrunt57** [custom-components/alexa_media_player#1104]
This would be nice rather than having to code a templated entity...
```
service: media_player.play_media
data:
  entity_id: '{{ states.sensor.last_alexa.state }}'
  media_content_id: Alexa.GoodMorning.Play
  media_content_type: sequence
```
