### ISSUE TITLE
Play Sound

### ISSUE THREAD

**Issue by oneseventhree** [custom-components/alexa_media_player#1199]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
I can get this to work:
```
door_bell_alexa:
  sequence:
    - service: media_player.play_media
      data:
        entity_id: media_player.guest_room
        media_content_type: sound
        media_content_id: amzn_sfx_doorbell_chime_01
 ```
But all the other sounds I want to use don't work. Is there a way to play other sounds that aren't just in the "known sounds" section? Maybe even play something from local?

**Describe the solution you'd like**
Is there a reason we can't play all sounds in the Amazon Lib?

**Describe alternatives you've considered**
There is no way to play local sounds to external speakers like a BEEP or CLICK sound with HA.

**Additional context**
