### ISSUE TITLE
[Support]

### ISSUE THREAD

**Issue by TheDarthFather** [custom-components/alexa_media_player#1216]
Hello,
This is not a bug, but rather an issue I have with 3 out of my 4 echos.
I made a simple lovelace card like the one below.
Works perfectly on one of my echo's ... but when I try the same on the other 3, Alexa is saying that she "does not know how to to that". 
If I just say "Alexa, Plax XXX FM", she is launching the radio from TuneIn like a charm.
Is there any setup I am missing on my other 3 echo's ?

```
type: entities
entities:
  - input_select.media_source
  - entity: media_player.master_echo
    tap_action:
      action: call-service
      service: media_player.play_media
      service_data:
        media_content_id: |
          {% if is_state("input_select.media_source", "XXX FM") %}
              Play XXX FM
        media_content_type: custom
        entity_id: media_player.master_echo
```
