### ISSUE TITLE
Old Guy Needs a Hint

### ISSUE THREAD

**Issue by snug-inglenook** [custom-components/alexa_media_player#1258]
Ok, here I am asking anybody to help with creation a simple automation with my Alexa:
On certain time and day I want all my Alexas play a radio from Tunein BUT I need them to use different volume: living room vol. X, kitchen vol. Y and so on. 
I read the documentation, but quite frankly I didn't understand much, as - despite being retired - I am a beginner here.
Very grateful

**Comment by snug-inglenook** [comment]
Just a follow up - I DID IT! Now it's working the way I wanted!

**Comment by alandtse** [comment]
Glad you for it working. You may want to share it on the wiki in case anyone has the same problem.

**Comment by snug-inglenook** [comment]
Not sure if this is the most efficient way, but here is how I did it:
IF there is a better way, please correct me
```
alias: BBC Saturday
description: ''
trigger:
  - platform: time
    at: '09:59:00'
condition: []
action:
  - service: media_player.volume_set
    data:
      volume_level: 0.4
    target:
      entity_id: media_player.living_room
  - service: media_player.volume_set
    data:
      volume_level: 1
    target:
      entity_id:
        - media_player.kitchen
  - service: media_player.volume_set
    data:
      volume_level: 0.1
    target:
      entity_id:
        - media_player.hallway
        - media_player.bathroom
  - service: media_player.volume_set
    data:
      volume_level: 0.1
    target:
      entity_id: media_player.office
  - service: media_player.play_media
    data:
      media_content_id: BBC
      media_content_type: TUNEIN
    target:
      entity_id:
        - media_player.living_room
        - media_player.kitchen
        - media_player.hallway
        - media_player.bathroom
        - media_player.office
  - delay:
      hours: 6
      minutes: 7
      seconds: 0
      milliseconds: 0
  - service: media_player.media_stop
    target:
      entity_id:
        - media_player.bathroom
        - media_player.hallway
        - media_player.kitchen
        - media_player.living_room
        - media_player.office
mode: single
```
