### ISSUE TITLE
notify.alexa_media service don't wait message end anymore

### ISSUE THREAD

**Issue by energywave** [custom-components/alexa_media_player#1365]
5 or 6 months ago I wrote a script to notify through HA app and Alexa (and I wrote a [post on my blog](https://henriksozzi.it/2021/03/script-con-parametri-opzionali-in-home-assistant/) about that)
It was working this way:

1. it read the Alexa current volume and store it to an input_number
2. It set the specified volume for the announcement 
3. It play the announcement using the notify.alexa_media service with type: announce
4. It revert the volume with the one stored in the input_number of point 1

It worked like a charm until some time ago (didn't remember how much)
Now you can see that all the commands are executed but the announcement is not wait for the end so that the second media_player.volume_set is executed in fact BEFORE the announcement is taking place.

I can ensure that in the past the volume_set was AFTER the announcement was done.

If it's a change in the component may I ask a parameter for that? Something like synchro: true to ensure that the sequence will wait the end of the announce to proceed with the next sequence command.

I'm at last version of alexa_media_player and Home Assistant ver 2021.9.4 running in Home Assistant OS on a Raspberry Pi 4 4GB.

**Comment by dvbit** [comment]
Can confirm the behaviour.

**Comment by alandtse** [comment]
If you're talking about a HA sequence whether script or automation, we don't control that. You'll have to raise it with Core. You can probably add some more delays.

**Comment by energywave** [comment]
I don't know the internals as I don't code in Python (should absolutely learn it one day or another...) but yes, I'm referring to HA sequences in scripts or automations. Are you saying that the integration doesn't have a control to wait to return control to HA to proceed with the next command in the sequence? Is HA launching asynchronously every command? So is that due to a change inside the core and not in your integration?

**Comment by dvbit** [comment]
It is anyway quite strange as it was waiting the message end before. One of this 3 things changed: integration, alexa, homeassistant :-(

**Comment by alandtse** [comment]
Well since we haven't changed code here for 2 months, I'm pretty sure it's not this integration.

**Comment by dvbit** [comment]
Fair enough :-) so we have two other suspects. Home assistant which changed quite a lot in the last  2 months  and alexa on which we have no control at all. So... lets see what changes could impact in ha inthe last 2 months. @energywave  the alternative would be to change the logic of the script to manage it. Delays i think are not a practical way as the announcement is if variable length.

**Comment by energywave** [comment]
Honestly I don't know how much time ago this changed. Could even be more than 2 months. Normally my echo dot are at 0.6 volume and so I use notifications so I didn't notice immediately that volume restore stopped working.
I can try to make some tests using a VM going back in time with HA and with this integration to understand at what point it stopped working and where. That way I can address a more precise information to the developer in charge.
@dvbit I this there is only one alternative: disable the volume restore. As you said messages are variable length and it would be too difficult to calculate it (and that would be a very empirical and ugly work around...)
I hope to better understand the issue as that approach (exposed in the issue body) was very useful to mimic an "announcement volume", different from the music volume. Much like Google has natively, if I remember correctly.

**Comment by energywave** [comment]
@alandtse please reopen this issue.
I did some test about the two way we have to pronounce notifications and I've found some interesting things. Here two sequences you can try and verify yourself:

```
script:
  alexa_test_announce:
    sequence:
      - service: media_player.volume_set
        target: 
          entity_id: media_player.mansarda
        data:
          volume_level: 0.8
      - service: notify.alexa_media
        data:  
          message: This is a test of a notification. In this case the volume will be very low as the command that follows will be executed BEFORE the anncounce.
          data:
            type: announce
          target: media_player.mansarda
      - service: media_player.volume_set
        target:
          entity_id: media_player.mansarda
        data:
          volume_level: 0.2
```

And this:
```
script:
  alexa_test_tts:
    sequence:
      - service: media_player.volume_set
        target: 
          entity_id: media_player.mansarda
        data:
          volume_level: 0.8
      - service: notify.alexa_media
        data:  
          message: This is a test of a notification. In this case the volume will be loud as the sequence of actions will be respected.
          data:
            type: tts
          target: media_player.mansarda
      - service: media_player.volume_set
        target:
          entity_id: media_player.mansarda
        data:
          volume_level: 0.2
```

Well, as told in the message, the first script alexa_test_announce that's using **type: announce** will **not wait** the pronounced message to continue executing the next action, in this case volume_set.
The second script alexa_test_tts that's using **type: tts** will **wait** the pronounced message to continue executing the next action.

So it's not possible that the responsability of this is in the core as two different flavor of your notification are different each other.
Furthermore I was using type: announce from ever and it was waiting the message end as what's is doing now tts. So something changed and that's not the core as, again, tts is doing it correctly.

Please take a look at this. The backup / restore of previous volume is so useful...
