### ISSUE TITLE
Echo Dot - TTS not working

### ISSUE THREAD

**Issue by stefanstranger** [custom-components/alexa_media_player#1411]
**Describe the bug**
My Echo Dot 3 is being discovered and I've and I see 7 entities, where some of the entities show as unavailable.

![image](https://user-images.githubusercontent.com/2125385/141443373-d69bdf7c-16e7-42bf-96b7-60c216fa9766.png)

I'm testing TTS using microsoft_say which is working for my Sonos speakers but I just don't get any sound (speech) from my Echo Dot.

I tested it via the Development Tools in HA using the following code:

```yaml
service: notify.alexa_media
data:
  message: "Hello World"
  target: media_player.stefan_s_echo_dot
  data:
    type: microsoft_say
```

**Expected behavior**
TTS is working for my discovered Echo Dot.

**System details**
 - Home-assistant (version): 2021.9.7
 - Hassio (Yes): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup): 3.10.10
 - alexapy (version from `pip show alexapy` or HA startup):
    I cannot run pip show alexapy on my Home Assistant. pip is not installed. A search for alexypy also didn't find any files with this name.
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: 

**Logs**
I've enabled logging in my configuration.yaml as follows, but I don't see any logs I can share. 

```yaml
    custom_components.alexa_media: debug  
    # for API debugging (verbose and intended for service debugging)
    alexapy: debug
    # for proxy debugging
    authcaptureproxy: debug
```
