### ISSUE TITLE
Audio tag to play MP3 file does not work

### ISSUE THREAD

**Issue by stefanstranger** [custom-components/alexa_media_player#1412]
**Describe the bug**
I'm trying to use the Alexa Skills SSML Audio tag reference to have an external hosted mp3 file being played. But the text is being spoken but the audio mp3 file is not being played.

More information about the audio tag can be found [here](https://developer.amazon.com/en-US/docs/alexa/custom-skills/speech-synthesis-markup-language-ssml-reference.html#audio).

**To Reproduce**
1. Open Development Tools in Home Assistant
2. Try to execute the following yaml code:
```yaml
service: notify.alexa_media
data:
  message: >-
    Play doorbell.
    <audio src="https://www.stranger.nl/doorbell-2.mp3"/>
    Did you hear the doorbell ring?
  data:
    type: announce
    method: all
  target:
  - media_player.stefan_s_echo_dot
```
3. You should hear the messages spoken, but the mp3 is not being played.

**Expected behavior**
Besides the message text being spoken the doorbell-2.mp3 should also being played.

**Screenshots**

**System details**
 - Home-assistant (version): 2021.9.7
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): 3.10.10
 - alexapy (version from `pip show alexapy` or HA startup): 1.25.1
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). Yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

I converted the mp3 file as described by the link from Alexa Skills.

**Comment by alandtse** [comment]
What happens if you try in the app using the ssml? We use the same API call as the app so if it doesn't work there, we can't help here.

**Comment by stefanstranger** [comment]
Hi Alan,

Thanks for your response. Which app do you mean?

**Comment by alandtse** [comment]
Alexa mobile app.

**Comment by Giancky79** [comment]
i reproduce mp3 with type: tts

**Comment by alandtse** [comment]
Please show your service call that worked so others can replicate it.

**Comment by Giancky79** [comment]
```
action:  
  - variables:
      url: !secret external_url
  - service: media_player.volume_set
    data:
      entity_id: >
        {{states('input_select.alexa_wakeup_speaker')}}
      volume_level: >
        {{ states('input_number.ringtones_level')}}
  - service: notify.alexa_media
    data: 
      target: >
        {{states('input_select.alexa_wakeup_speaker')}}
      data:
        type: tts
      message: >
        <audio src='{{url}}/local/audio/ringtones/{{states('input_select.ringtones')}}.mp3'/>
```

i like's with template but if you want normal

put

 `<audio src='https://domain/local/audio/ringtones/audio.mp3'/>`

with 443 no need :port, different with 812x
 
but alexa need a clean mp3, for this problem you have 2 solution

The first with linux
```
ffmpeg -i <input-file> -ac 2 -codec:a libmp3lame -b:a 48k -ar 16000 -write_xing 0 <output-file>
to sample rate 16000

```
```
ffmpeg -i <input-file> -ac 2 -codec:a libmp3lame -b:a 48k -ar 24000 -write_xing 0 <output-file>
to sample rate 24000
```

but i'm too lazy, and i prefer the 2th solution

[https://v3.jovo.tech/audio-converter](url)
