### ISSUE TITLE
attributes.last_called is not updated

### ISSUE THREAD

**Issue by sorinUrziceanu** [custom-components/alexa_media_player#1453]
**Describe the bug**
I'm trying to use the last_alexa as was described, but the problem is that the attributes.last_called is not updated. Each time I get the same last_alexa, doesn't matter to which dot I'm speaking.

groups.yaml

```
  echos:
    name: All Echos
    entities:
      - media_player.phone
      - media_player.echo_dot
      - media_player.fire
```

template.yaml

```
  - sensor:
      - name: last_alexa
        state: >
          {{ expand('group.echos') | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first }}
```

scripts.yaml

```
  alexa_id_test:
    sequence:
      - service: notify.alexa_media
        data_template:
          message: >
            Value is {{ states('sensor.last_alexa') }}
          target: "{{ states('sensor.last_alexa') }}"
        data:
          data:
            type: tts
```

**To Reproduce**
For example, I'm executing the script by speaking to Alexa from my phone. After the execution the message: "Value is media_player.echo_dot" is read by my echo_dot device instead of my phone. If I restart the hassio, sometimes is read by the phone every time doesn't matter to which device I'm speaking. Seems that it remain the first selected device and never update to the last_called.

**Expected behavior**
The last device to which I'm speaking should respond

**System details**
 - Home-assistant (version): core-2021.9.7
 - alexa_media  (version from `const.py` or HA startup): 3.10.0
