### ISSUE TITLE
Routines are not reliably firing when multiple scripted

### ISSUE THREAD

**Issue by alandtse** [custom-components/alexa_media_player#147]
@alandtse my routines still don't work a 100% reliable. Sometimes it doesn't work at the first try, but it does always at the second one.

_Originally posted by @h4nc in https://github.com/keatontaylor/alexa_media_player/issues/90#issuecomment-477928939_

**Comment by h4nc** [comment]
This is the script where tts often fails at the first try, when running the routine on an alexa device that was not `last_called = true` before.

in script.yaml

```
alexa_routine_wm:
  sequence:
    - service: notify.alexa_media
      data_template:
        target: '{{ states.sensor.last_alexa.state }}'
        message: >
          {% if is_state("binary_sensor.waschmaschine_state", "on") %}
            Die Waschmaschine läuft noch
          {% else %}
            Die Waschmaschine ist aus
          {% endif %}         
        data:
          type: tts
```

automation.yaml

```
- alias: Alexa Routinen Waschmaschine - 1
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: light.alexa_dummy
    to: 'on'
  condition:
    - condition: template
      value_template: '{{ states.light.alexa_dummy.attributes.brightness == (1 * 255)//100 }}'
  action:
    - delay:
        seconds: 0.5  
    - service: alexa_media.update_last_called 
    - delay:
        seconds: 0.5  
    - service: script.turn_on
      entity_id: script.alexa_set_volume
    - delay:
        seconds: 0.5          
    - service: homeassistant.turn_on
      entity_id: script.alexa_routine_wm
    - service: homeassistant.turn_off
      entity_id: light.alexa_dummy
```

**Comment by h4nc** [comment]
I have to add that most of the time, when tts fails the volume set works. So it actually know that this device was ist the new "last called" device. But somehow it is sometimes to slow to perform the tts after that volume set.

**Comment by alandtse** [comment]
@h4nc If you create a test script that just performs the three alexa actions with the delays, does that script have the same problem consistently?
```yaml
    - delay:
        seconds: 0.5  
    - service: alexa_media.update_last_called 
    - delay:
        seconds: 0.5  
    - service: script.turn_on
      entity_id: script.alexa_set_volume
    - delay:
        seconds: 0.5          
    - service: homeassistant.turn_on
      entity_id: script.alexa_routine_wm
```

What's your `script.alexa_set_volume`?

I'd also like to verify that it's tied to `last_called`. Can you please try the scripts without the `update_last_called`. Let's just manually set the target to a specific Alexa device in both `script.alexa_set_volume` and `script.alexa_routine_wm` and run the test script.

**Comment by h4nc** [comment]
this is my script.alexa_set_volume:

```
alexa_set_volume:
  sequence:
    - service: media_player.volume_set
      data_template: 
        entity_id: '{{ states.sensor.last_alexa.state }}' 
        volume_level: >
          {% if is_state("sensor.last_alexa", "media_player.echo_dot_2gen") %}
            0.8
          {% else %}
            0.3
          {% endif %} 
```

The second gen echo dot is much quieter than other devices so I need this to set the volume different. 

Ok, so know I changed my automation and my script. As you advised all off the commands I had in the autmoations action section before are now in the script. I also commented out the last_alexa service and set a specific device.

I will come back when I tested everything.

**Comment by h4nc** [comment]
Ok, so I already testet it. 

The script again did not work reliable. So as you assumed last_alexa shouldn't be the issue here. What else can I test?
In all (well let's say nearly 100%) of that tests the volume set works.

**Comment by h4nc** [comment]
@alandtse with the recent update to version 1.2.4 it seems like the issues are gone.

Normally after not calling a routine for a while it doesn't work realiable by nearly a 100 % chance.

Since the update I tried it 3 times (with some hours pause in between) and it worked every time.

Did something change in the newest version that could have fixed this?

**Comment by alandtse** [comment]
Actually no. Unless the issue was you have many routines and for some reason they were being returned in different orders. I believe we weren't able to execute routines beyond 20 because we only got a single page of routines from Amazon before 1.2.4.

Let's leave this open for a few more days to see if it comes back.

**Comment by h4nc** [comment]
Hopefully it is gone.

I have 15 routines, so to much shouldn’t be the issue here.

Ok lets see if it comes back.

**Comment by h4nc** [comment]
ok issue isn't gone, tried it again today and it did set the volume but it didn't send a tts message.

**Comment by alandtse** [comment]
@h4nc There's currently an update staged for [alexapy](https://gitlab.com/keatontaylor/alexapy/merge_requests/92) that should try to queue multiple sequences at once. If you're on the latest version of alexa_media, please see if this helps.

**Comment by h4nc** [comment]
Did not try that yet, but I put a 3 second delay between the volume set and tts. Felt like this made it (much more) reliable.

**Comment by alandtse** [comment]
It's actually manifesting for people in different [ways](https://github.com/custom-components/alexa_media_player/issues/454).

**Comment by alandtse** [comment]
As a note, delays should no longer be necessary and in fact may disable the benefits of the queuing. Right now it'll wait 0.5 seconds to see if another command comes in.

**Comment by h4nc** [comment]
Ok, I will try commenting out all the delay and see how it works.

**Comment by h4nc** [comment]
Unfortunately it still doesn't work reliable. Did you try it yourself, does it work for you?


What it should do:
1) set volume
2) make announcement 

This is what happens totally random:
- announcement before setting volume
- volume before announcement
- set volume only
- announcement only

This is an example of the script I use in an automation:

```
alexa_set_volume:
  sequence:
    - service: media_player.volume_set
      data:
        entity_id: media_player.echo_dot
        volume_level: 0.3

wash_alexa:
  sequence:
    - service: script.turn_on
      entity_id: script.alexa_set_volume
    #- delay: '00:00:03'
    - service: notify.alexa_media
      data:
        target: media_player.echo_dot
        message: "Washing mashing finished"
        data:
          type: announce
          method: all
```

**Comment by alandtse** [comment]
@h4nc I didn't have the problem you experienced, but I did some manual tests to make sure items were queuing.

One thing worth testing is to increase the time the api waits for another command to come in and queue.  Right now I have it set for 0.5 seconds. It may be worth testing other larger values to see if it helps.

To do it, you'd have to change line [152 in alexapi.py](https://gitlab.com/keatontaylor/alexapy/merge_requests/92/diffs#dbe0d100d78c95aaf8447803831c8257d0bfdac6_148_152).

For example, if you changed it 1 second it'd be here:
```python
            queue_delay: float = 0.5,
```
to
```python
            queue_delay: float = 1,
```

**Comment by h4nc** [comment]
I just wanted to test this, but I'm afraid I not able to do it. I use hassio and I did not find alexapi in the components section (hacs install). 

Maybe someone else can join this (from the other issue).

**Comment by alandtse** [comment]
This should now be fully resolved as of 2.5.0.

**Comment by h4nc** [comment]
Just tested it and for me it still doesn't work correctly.

Now it looks like it does indeed fire both events reliable (volume and tts) but TTS mostly comes first although I first set the volume in the script.

**Comment by alandtse** [comment]
Odd, that shouldn't be the case. Can you get me the alexapy.alexaapi logs? There should be a "building sequence line". You should see the nodes for volume and TTS and they should appear in the order of when they'll be executed. It should be identical to a routine you can set in the app.

**Comment by h4nc** [comment]
Sure, but how do I get these?

With
```
logger: # wegen alexa debugging
  default: critical
  logs:
    custom_components.alexa_media: debug  
    alexapy: debug
```
?

**Comment by h4nc** [comment]
Sure, but how do I get these?

With
```
logger: 
  default: critical
  logs:
    custom_components.alexa_media: debug  
    alexapy: debug
```
?

**Comment by alandtse** [comment]
@h4nc Yes. It's possible you can get more detailed to only pull the alexapy.alexaapi logs, but I haven't tried it.

e.g.,
```yaml
logger: 
  default: critical
  logs:
    custom_components.alexa_media: debug  
    alexapy.alexaapi: debug

```

What you should be looking for is the queuing info.  I don't need anything really beyond seeing the queuing order of the Nodes.  There's a lot of info you should remove like `customerId` and `deviceSerialNumber`.

Below is an example where I just did 3 chimes in quick succession.
```
2020-01-16 01:34:02 DEBUG (MainThread) [alexapy.alexaapi] Creating sequence for 3 items
2020-01-16 01:34:02 DEBUG (MainThread) [alexapy.alexaapi] Running behavior with data: {"behaviorId": "PREVIEW", "sequenceJson": "{\"@type\": \"com.amazon.alexa.behaviors.model.Sequence\", \"startNode\": {\"@type\": \"com.amazon.alexa.behaviors.model.SerialNode\", \"nodesToExecute\": [{\"@type\": \"com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode\", \"type\": \"Alexa.Sound\", \"operationPayload\": {\"deviceType\": \"A3S5BH2HU6VAYF\", \"deviceSerialNumber\": \"XXXX\", \"locale\": \"en-us\", \"customerId\": \"XXX\", \"soundStringId\": \"amzn_sfx_doorbell_chime_01\", \"skillId\": \"amzn1.ask.1p.sound\"}}, {\"@type\": \"com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode\", \"type\": \"Alexa.Sound\", \"operationPayload\": {\"deviceType\": \"A3S5BH2HU6VAYF\", \"deviceSerialNumber\": \"XXX\", \"locale\": \"en-us\", \"customerId\": \"XXX\", \"soundStringId\": \"amzn_sfx_doorbell_chime_01\", \"skillId\": \"amzn1.ask.1p.sound\"}}, {\"@type\": \"com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode\", \"type\": \"Alexa.Sound\", \"operationPayload\": {\"deviceType\": \"A3S5BH2HU6VAYF\", \"deviceSerialNumber\": \"XXX\", \"locale\": \"en-us\", \"customerId\": \"XXX\", \"soundStringId\": \"amzn_sfx_doorbell_chime_01\", \"skillId\": \"amzn1.ask.1p.sound\"}}]}}", "status": "ENABLED"}
```

**Comment by h4nc** [comment]
I think I found the issue. So this is what I used:

```
wash_alexa:
  alias: Alexa - washing machine  
  sequence:
    - service: script.turn_on
      entity_id: script.alexa_set_volume_livingroom
    - service: notify.alexa_media
      data:
        target: media_player.echo_dot_livingroom
        message: "Washing machine finished"
        data:
          type: announce
          method: all

alexa_set_volume_livingroom:
  sequence:
    - service: media_player.volume_set
      data:
        entity_id: media_player.echo_dot_livingroom
        volume_level: 0.3 
```         

I used script.alexa_set_volume_livingroom to make the code shorter. After changing it to:

```
wash_alexa:
  alias: Alexa - washing machine  
  sequence:
    - service: media_player.volume_set
      data:
        entity_id: media_player.echo_dot_livingroom
        volume_level: 0.3  
    - service: notify.alexa_media
      data:
        target: media_player.echo_dot_livingroom
        message: "Washing machine finished"
        data:
          type: announce
          method: all
```

It seems like it works now (4 tests). Thanks! Do you know why it doesn't work with the script in the script?


BTW would it be possible to 

- read/store volume setting
- set new volume setting
- tts 
- set to old volume setting again

This would be great when you listening to some music and a TTS comes in. But first let’s get rid of the other issue. 

PS: already had the logs but not scratched yet and it seems like they aren't needed any more.

**Comment by h4nc** [comment]
I think I found the issue. So this is what I used:

```
wash_alexa:
  alias: Alexa - washing machine  
  sequence:
    - service: script.turn_on
      entity_id: script.alexa_set_volume_livingroom
    - service: notify.alexa_media
      data:
        target: media_player.echo_dot_livingroom
        message: "Washing machine finished"
        data:
          type: announce
          method: all

alexa_set_volume_livingroom:
  sequence:
    - service: media_player.volume_set
      data:
        entity_id: media_player.echo_dot_livingroom
        volume_level: 0.3 
```         

I used script.alexa_set_volume_livingroom to make the code shorter. After changing it to:

```
wash_alexa:
  alias: Alexa - washing machine  
  sequence:
    - service: media_player.volume_set
      data:
        entity_id: media_player.echo_dot_livingroom
        volume_level: 0.3  
    - service: notify.alexa_media
      data:
        target: media_player.echo_dot_livingroom
        message: "Washing machine finished"
        data:
          type: announce
          method: all
```

It seems like it works now (4 tests). Thanks! Do you know why it doesn't work with the script in the script?


BTW would it be possible to 

- read/store volume setting
- set new volume setting
- tts 
- set to old volume setting again

This would be great when you listening to some music and a TTS comes in. 

PS: already had the logs but not scratched yet and it seems like they aren't needed any more.

**Comment by alandtse** [comment]
> It seems like it works now (4 tests). Thanks! Do you know why it doesn't work with the script in the script?

I think HA doesn't guarantee that scripts that call async components will **finish** before the next step is performed. I think the only guarantee is that the next step won't **start** before the prior step starts. 

Because the component is async, it's possible that the set volume script is started before the next step, but the volume is being sent after the next step of the original script, which is the tts call.

I believe there have been people who posted in the forum and perhaps in the automations in the wiki where they saved the volume level before making a change.  I don't do it myself, but I think you can find it if you look.

I'll close this out finally since we seem to have resolved it.

**Comment by h4nc** [comment]
Today I noticed that firing multiple routines stopped working for me again, although I changed my scripts like mentioned above and they worked fine for a while. 

So this is what I use:

```
wash_alexa:
  alias: Alexa - washing machine  
  sequence:
    - service: media_player.volume_set
      data:
        entity_id: media_player.echo_dot_livingroom
        volume_level: 0.3  
    - service: notify.alexa_media
      data:
        target: media_player.echo_dot_livingroom
        message: "Washing machine finished"
        data:
          type: announce
          method: all
```

Tried this on the living room echo. It reliable changes the volume there, but no TTS.
Same script for another echo (both echo dot 3) ignores the set volume command and only fires the TTS.

Did something change in the last versions that could cause this? @alandtse could you please reopen this
