### ISSUE TITLE
Announce only work in Echo Show

### ISSUE THREAD

**Issue by oalbaf** [custom-components/alexa_media_player#1473]
**Describe the bug**
The notify.alexia_media service works fine on my Echo Show 5 and 8. But on an Echo 2Gen only TTS notifications work. The 'announce' notifications are ignored by this device. It does not produce an error message in the log.

Previously it worked. An Announce notification produced a voice message on the Echos and a voice + text message on the Echo Show. Now it's only works on Echo Show.

**To Reproduce**
This script only works in Echo Show:
```
tts_house_temp:
  alias: TTS Temperatura de casa
  sequence:
    - service: alexa_media.update_last_called
    - service: notify.alexa_media
      data:
        target: "{{ states('sensor.last_alexa') }}"
        data:
          type: announce
        message: >
          En el exterior tenemos una temperatura de {{states('sensor.temperature_exterior')}} grados, 
          y la temperatura media interior es de {{states('sensor.average_temperature')}} grados.
```

This script works fine in all Echo devices. Only change type to tts:
```
tts_house_temp:
  alias: TTS Temperatura de casa
  sequence:
    - service: alexa_media.update_last_called
    - service: notify.alexa_media
      data:
        target: "{{ states('sensor.last_alexa') }}"
        data:
          type: tts
        message: >
          En el exterior tenemos una temperatura de {{states('sensor.temperature_exterior')}} grados, 
          y la temperatura media interior es de {{states('sensor.average_temperature')}} grados.
```

**Expected behavior**
Can you help me get announce to work properly on all Echo devices? I don't want to lose the on-screen text of the Show by making my notifications compatible with all Echo devices.

**System details**
Home Assistant 2021.12.4
 - alexa_media  (version from `const.py` or HA startup): 3.10.15
 - alexapy (version from `pip show alexapy` or HA startup): I don't known
 - Amazon [2FA is enabled]: yes

**Logs**
It does not show any message in the Home Assistant log
