### ISSUE TITLE
Annoying Announcements from Amazon

### ISSUE THREAD

**Issue by tunerooster** [custom-components/alexa_media_player#1504]
This is kind of a follow up to my issue re: opening the Silk browser:

Using:
```
    - service: media_player.play_media
      data:
        entity_id: media_player.my_echo_show
        media_content_id: 'open mypage'
        media_content_type: custom
```
I am now able to have Alexa automatically open my HA dashboard via a trigger, which is progress!  There remains one small problem:
- If I say "open mypage" using my voice (not the automation), Alexa _silently_ opens Silk to my configured url (perfect!).
- However, if I trigger "open mypage" using the above automation, it announces "OK, Here's mypage".
- This would not be a problem, except that, due to limitations imposed by Amazon, after 5 minutes, it closes my page and reverts to is home screen.  There is no way around this that I have found.
- So... I have to restart "open mypage" every 5 minutes, and every 5 minutes, it announces "Here's mypage", which is vary annoying and unacceptable to my wife.
- I have tried setting the volume to 0, but the announcement forcefully turns the volume up before saying "Here's mypage".
**So my question is, if triggering "open mypage" using my voice works with *no announcement*, perhaps there is a setting which can disable the announcement via the Alexa Media Player?**

Here's hoping...

Thanks!
