### ISSUE TITLE
Can't turn screen back on

### ISSUE THREAD

**Issue by tunerooster** [custom-components/alexa_media_player#1513]
Sorry, but I am stumped here...

I run this:
```
service: media_player.play_media
target:
  entity_id: media_player.my_echo_show
data:
  media_content_id:  screen off
  media_content_type: custom
```
And the screen turns off (as expected).  But when I run this:
```
service: media_player.play_media
target:
  entity_id: media_player.my_echo_show
data:
  media_content_id:  screen on
  media_content_type: custom
```
I.e., "screen on" to try to turn it back on, and nothing happens, the echo show **_screen remains off._**  I am trying to turn it `off` at night and `on` in the morning (via automation).

**Is there another way to do this?**

Thanks!
