### ISSUE TITLE
"Url not relative" error when targeting area_id with play_media

### ISSUE THREAD

**Issue by atv2016** [custom-components/alexa_media_player#1577]
**Describe the bug**
I am getting this in the logs:
Unexpected error for call_service at pos 1: URL is relative, but does not start with a /

YAML is simple enough:
```yaml
- id: '1638533164647'
  alias: Weekend relaxing music afternoon
  description: Play weekend relaxing music at sunset
  trigger:
  - platform: sun
    event: sunset
    offset: '0'
  condition:
  - condition: time
    weekday:
    - sat
    - sun
  action:
  - service: media_player.play_media
    target:
      area_id: dining_room
    data:
      media_content_id: shuffle relaxing music playlist everywhere
      media_content_type: AMAZON_MUSIC
  mode: single
```

**To Reproduce**
Steps to reproduce the behavior: See above

**Expected behavior**
Not get this message
**Screenshots**

**System details**
 - Home-assistant (version): Latest, core-2022.4.7,supervisor-2022.04.0
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).

No, supervised. I used a VM as per the first section in this page: https://www.home-assistant.io/installation/linux

 - alexa_media  (version from `const.py` or HA startup): Latest, v3.11.2

 - alexapy (version from `pip show alexapy` or HA startup): pip show alexapy shows me:
 package not found when open a terminal

 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: Yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

Logger: homeassistant.components.automation.weekend_relaxing_music_afternoon
Source: components/media_player/browse_media.py:43 
Integration: Automation (documentation, issues) 
First occurred: 20:13:40 (2 occurrences) 
Last logged: 20:13:40

Weekend relaxing music afternoon: Error executing script. Unexpected error for call_service at pos 1: URL is relative, but does not start with a /
While executing automation automation.weekend_relaxing_music_afternoon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 379, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 582, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1634, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1671, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 677, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 955, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 714, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 643, in async_play_media
    media_id = async_process_play_media_url(self.hass, media_id)
  File "/usr/src/homeassistant/homeassistant/components/media_player/browse_media.py", line 43, in async_process_play_media_url
    raise ValueError("URL is relative, but does not start with a /")
ValueError: URL is relative, but does not start with a /

**Additional context**
