### ISSUE TITLE
Cannot address my Echo Flex properly  - other device plays back

### ISSUE THREAD

**Issue by VilemP** [custom-components/alexa_media_player#1603]
**Describe the bug**
Hello. I have recently bought a new Echo Flex device.  It was successfully imported. However, I did not like the id, and therefore I have changed the entity id in the home assistant. (I don't know whether that is relevant, just mentioning that for completeness).
I am unable to media_player.play_media on that device though. Instead, when I call the service, it starts to play on the device that was originally used for that. I can't figure out what is wrong. Tried to do full uninstall and fresh install with no success.

Basically, when I call:

```
service: media_player.play_media
data:
  media_content_id: Milano Lounge
  media_content_type: TUNEIN
target:
  entity_id: media_player.downstairs_bathroom_flex
```
or 

```
service: media_player.play_media
data:
  media_content_id: Milano Lounge
  media_content_type: TUNEIN
target:
  entity_id: media_player.extra_echo_dot
```
it always plays on extra echo dot device, not on the flex device :-(

**To Reproduce**
I don't know whether it is reproducible by you. 

**Expected behavior**
I expect the music to play on the targeted device

**System details**

Home Assistant Core 2022.5.5
Home Assistant Supervisor 2022.05.2
Home Assistant OS 8.1
Kernel version 5.15.41
 - Home-assistant (version): 
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug). ?
 - alexa_media  (version from `const.py` or HA startup): 3.11.3 ?
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered:  2FA enabled

**Comment by VilemP** [comment]
Some more info. Went through logs and this is what I found:

```
2022-05-22 14:03:29 DEBUG (MainThread) [custom_components.alexa_media] m***********a@b**********z: Received websocket command: PUSH_AUDIO_PLAYER_STATE : {'destinationUserId': 'A**********07Q', 'dopplerId': {'deviceType': 'A1RABVCI4QCIKC', 'deviceSerialNumber': 'G************4MC'}, 'audioPlayerState': 'PLAYING', 'quality': None, 'error': False, 'errorMessage': None, 'mediaReferenceId': 'b339f714-8392-411a-b57c-f6818b167874:1'}
```

after calling 

```
service: media_player.play_media
data:
  media_content_id: Milano Lounge
  media_content_type: TUNEIN
target:
  entity_id: media_player.downstairs_bathroom_flex
```

The data from the amazon API:

```
    {
      "accountName": "Extra Echo Dot",
      "appDeviceList": [],
      "deviceAccountId": "A*****NDR",
      "deviceFamily": "ECHO",
      "deviceOwnerCustomerId": "A*****07Q",
      "deviceType": "A****IKC",
      "deviceTypeFriendlyName": null,
      "essid": null,
      "language": null,
      "macAddress": null,
      "online": true,
      "parentClusters": [],
      "postalCode": null,
      "registrationId": null,
      "remainingBatteryLevel": null,
      "serialNumber": "G***4MC",
      "softwareVersion": "7148109188"
    }
```    
  
Note that the serial Id in amazon matches the device, that actually plays. So, it seems, that for some reason, wrong serial id of the device is send over to Amazon.  No idea why.

Looking further into the logs, this looks suspicious:

```
2022-05-22 14:17:18 DEBUG (MainThread) [custom_components.alexa_media.media_player] m***********a@b**********z: Extra Echo Dot: Last_called check: self: G************4MC reported: G************8AG
```
the reported value equals to serial id of my Flex device, self equals to the Echo Dot device.
