### ISSUE TITLE
Failure when issuing custom command to play a radio station via Tune In

### ISSUE THREAD

**Issue by lits101** [custom-components/alexa_media_player#1709]
**Describe the bug**
When issuing a custom command to play a radio station via Tune In, I get a variety of errors spoken by the target Echo device including: 
 - "I cannot play that on Tune In" (when trying to play ABC Classic)
 - "The station named Radio National Brisbane is currently unavailable on Tune In"

Commands used:

```
service: media_player.play_media
data:
  media_content_id: Radio National upstairs
  media_content_type: TUNEIN
target:
  entity_id: media_player.study_dot
```

```
service: media_player.play_media
data:
  media_content_id: Play Radio National from Tune In upstairs
  media_content_type: custom
target:
  entity_id: media_player.study_dot
```

This was working until a few days ago. First noticed it not working on the morning of Sunday 4 September 2022 AEST. 

When speaking the same command directly to an Echo device, the device will play the station as is intended. 

E.g "Alexa, play Radio National Brisbane on Tune In"

**To Reproduce**

    Go to 'Services' under 'Developer Tools'
    Use one of the two config examples above with your Echo device as the target
    Click 'Call Service' 
    Hear error from your Echo device!

**Expected behavior**
Should play the station via Tune In
