### ISSUE TITLE
BBC Radio has stopped working in Alexa Media player.

### ISSUE THREAD

**Issue by LindsayReid** [custom-components/alexa_media_player#1747]
Until today (20221005) I have been able to use:

service: media_player.play_media
data:
  media_content_id: play BBC Radio 4
  media_content_type: custom
target:
  entity_id:
    - media_player.echo_dot

This no longer works although other non-BBC stations I have tried still seem ok.

**Comment by N1c093** [comment]
I also noticed, that it's not working to play radio with a custom command.

I'm using this custom command and Alexa only answers "I'm not sure"

```yaml
data:
  media_content_id: Spiel NDR 2 auf Wohnung
  media_content_type: custom
service: media_player.play_media
entity_id: media_player.wohnzimmer
```
