### ISSUE TITLE
Play PLEX Audio

### ISSUE THREAD

**Issue by Jonopoly** [custom-components/alexa_media_player#1870]
Would it be possible to play audio from a local plex server? I've got some audiobooks for my kids to listen to whilst they're going a sleep Would be nice if I could let them choose their own books to listen to via alexa at the moment I can do a work around like

```yaml
service: media_player.play_media
target:
  entity_id: media_player.kids_alexa
data:
  "media_content_id": 'ask plex to play Audiobook name'
  "media_content_type": custom
```

but would be nice If it could be a bit more simpler like.. Spotify or Deezer sample

```
entity_id: media_player.kids_s_alexa
media_content_id: audiobook_the_bfg
media_content_type: PLEX
```
