### ISSUE TITLE
SSML Prosody Volume not working?

### ISSUE THREAD

**Issue by criticallimit** [custom-components/alexa_media_player#1898]
Played around with notify. alexa_media
Some of the SSML and also amazon:effect is working. But all about volume is noch working.

```
service: notify.alexa_media
data:
  message: <speak> <prosody volume="+3dB"> Motion detected in backyard</prosody><prosody pitch="low"> Motion detected in backyard</prosody></speak>
target: media_player.wohnzimmer
  data:
    type: tts
```

Doesn´t matter which prosody volume is in the code, volume stays the same but pitch is working.
Any ideas?
