### ISSUE TITLE
Custom commands no longer work

### ISSUE THREAD

**Issue by Stooovie** [custom-components/alexa_media_player#1995]
**Describe the bug**

any command with `media_content_type: custom` will not work. Nothing happens at all.

**To Reproduce**

1. go to HA Developer tools
2. run this service:
```
service: media_player.play_media
target:
  entity_id: media_player.YOURECHODEVICE
data:
  media_content_type: custom
  media_content_id: 'what time is it'
```

**Expected behavior**

the command to be carried out

**System details**

- Home-assistant (version): 2023.8
- alexa_media (version from `const.py` or HA startup): 4.6.5
- alexapy (version from `pip show alexapy` or HA startup): 1.26.8
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) Y. :

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

https://transfer.sh/wdfozF0jFz/home-assistant_alexa_media_2023-08-03T07-06-12.873Z.log

**Additional context**
