### ISSUE TITLE
information is not updating

### ISSUE THREAD

**Issue by herveaurel** [custom-components/alexa_media_player#2011]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

For several weeks, the integration has not updated the information, for example: the state of music, alarms, other sensors, switches, etc...
The only method I've found is to reload the integration manually, every now and then, but I don't have the right information between reloads.

I asked other users, and they have the same problem.

Because of this, the integration is not reliable for automations regarding music, alarms etc...

I don't see anything in the logs.

**To Reproduce**

1. Play music on an echo
2. set an alarm
3. consult home assistant
4. see that no information is up to date

**Expected behavior**

I hope that, like several weeks ago, all the information comes back into Home Assistant immediately

**Screenshots**

none

**System details**

- Home-assistant (version): 2023.8.4
- alexa_media (version from `const.py` or HA startup): 4.6.5
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : yes is enable

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).
I didn't see any logs

**Additional context**

none

**Comment by M3d1c5** [comment]
I have been experiencing this problem since 31.8. I have an automation that becomes active as soon as the volume of an Echo Dot is changed. This automation no longer works.

```
alias: Echo Gäste-WC Lautstärke
description: ""
trigger:
  - platform: state
    entity_id:
      - media_player.echo_gaste_wc
    attribute: volume_level
    for:
      hours: 0
      minutes: 3
      seconds: 0
condition: []
action:
  - service: media_player.volume_set
    data:
      volume_level: 0.1
    target:
      entity_id: media_player.echo_gaste_wc
mode: single
```
