### ISSUE TITLE
Alexa not sending notification to everywhere

### ISSUE THREAD

**Issue by rodolfomachado** [custom-components/alexa_media_player#2098]
Hi,

When I try to send notification to group everywhere it does not send it at all.

I'm using the following code:

```
          - service: notify.alexa_media_todo_lugar
            data:
              data:
                type: tts
              message: "{{ states('input_text.mensagem_para_alexa') }}"
```
My HA and alexa_media_player is up to date.

Btw, if I talk to Alexa and ask her to play any music in everywhere group it does work.
