### ISSUE TITLE
Alexa Guard hidden from the users in 2.1.0 if you use include for your devices

### ISSUE THREAD

**Issue by KennethLavrsen** [custom-components/alexa_media_player#340]
**Describe the bug**
After upgrading to 2.1.0 the Alexa Guard alarm panel feature seems gone.
My old entiry stopped working

And no new is created even after reinstallation and new pickle

In the release note there is a cryptic note that says "allow exclusions for alarm_control_panel and switches (169545f779d036a3c9a35dd150dafc8c657e0e12) - Use the full friendly name (e.g., "Master Bedroom repeat switch")"

But the link to the documentation about exclusions is the old that tells how to include and exclude devices. Nothing about guard or switches.

Why is the alexa guard gone? What is changed? How do I get it back?

**To Reproduce**
See above

**Expected behavior**
Expect to see Guard and misc switches like I did before

**Screenshots**

**System details**
 - Home-assistant (version): 0.98.2
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug). Yes and restarted many more times and removed / recreated pickle
 - alexa_media  (version from `const.py` or HA startup): 2.1.0 
 - alexapy (version from `pip show alexapy` or HA startup):  1.0.2

**Additional context**

My config is

```
alexa_media:
  accounts:
    - email: !secret alexa_account
      password: !secret alexa_password
      url: amazon.com
      include_devices:
        - "Echo Bedroom"
        - "Echo Bathroom"
        - "Echo Workshop"
        - "Echo Kitchen"
        - "Echo Living Room"
        - "Echo Office"
        - "Echo Portable"
        - "Echo Hallway"
```
