### ISSUE TITLE
Last Alexa Sensor - Stops Working

### ISSUE THREAD

**Issue by natedzl** [custom-components/alexa_media_player#391]
Hassio: 0.99.2
HACS Alexa Media Player: 2.2.1

The last alexa sensor seems to stop working after sometime (less than 1 day, longer than a few hours).  To restore the sensor functionality I have to restart Home Assistant.

Here's my config for the last_alexa sensor:
```
 # Last Called Echo Device
  - platform: template
    sensors:
      last_alexa:
        entity_id:
          - media_player.bedroom
          - media_player.kitchen
          - media_player.katelynn_s_room
          - media_player.valerie_s_room
          - media_player.noah_s_room
          - media_player.basement
          - media_player.baby_s_room
          - media_player.garage
        value_template: >
          {{ states.media_player | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first }}
```
I've summoned Alexa through 2 other devices this morning, but it fails to update the sensor:

![image](https://user-images.githubusercontent.com/54035704/65503999-b9c49780-de8b-11e9-8e40-c064770c2f1d.png)

After restarting Home Assistant, the sensor will update to the last called device during the period when it stopped updating the sensor.

Please let me know if you need anything further.
