### ISSUE TITLE
[Feature Request] - An option in config to disable Alexa options you won't use

### ISSUE THREAD

**Issue by skynet01** [custom-components/alexa_media_player#422]
**Is your feature request related to a problem? Please describe.**
This component is amazing and has grown to support many features. Some of the features create entities that Home assistant has to check. If you have many alexas in the house. For example i have 12 and each one of them creates a few sensors and switches Home Assistant gets slowed down (especially running on Pi3).

**Describe the solution you'd like**
Just have an option in config to disable features that you won't plan on using that create additional sensors / switches in Home Assistant.

For example

```
alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_password
      url: amazon.com
  disable:
   - timers
   - switches
   - alarm
   - reminder
```

**Describe alternatives you've considered**
You can disable entities manually in home assistant, you can only do it 1 by 1 and they are still technically in home assistant.
