### ISSUE TITLE
Invalid Date shown for reminders, timers, and alarms on Safari and iOS devices

### ISSUE THREAD

**Issue by mikeage** [custom-components/alexa_media_player#446]
**Describe the bug**
Lovelace's `entities` card shows `Invalid Date` for my upcoming events, even though they appear to have a valid time.

**To Reproduce**
`Alexa, set a reminder for ...`
Look at an `entities` card for `sensor.foo_next_reminder` (also alarm and timer, but the log here is a reminder).

**Expected behavior**
Proper time

**Screenshots**

**System details**
 - Home-assistant (version): 0.100.2
 - Hassio (Yes/No): no
 - alexa_media  (version from `const.py` or HA startup): 2.3.3 + #436
 - alexapy (version from `pip show alexapy` or HA startup): 

**Logs**
See https://pastebin.com/bu1EahUj

here's the card's `sorted_active` field:
```
[["0557be2d-30b8-3002-9d4d-6ba7c83ff173", {"alarmTime": 1571735940000, "automationId": null, "createdDate": 1571735383396, "deferredAtTime": null, "deliveryType": null, "deviceSerialNumber": "G090LF11827306AV", "deviceType": "A3S5BH2HU6VAYF", "extensibleAttribute": null, "geoLocationTriggerData": null, "id": "A3S5BH2HU6VAYF-G090LF11827306AV-0557be2d-30b8-3002-9d4d-6ba7c83ff173", "lastOccurrenceTimeInMilli": 0, "lastUpdatedDate": 0, "musicAlarmId": null, "musicEntity": null, "notificationIndex": "0557be2d-30b8-3002-9d4d-6ba7c83ff173", "originalDate": "2019-10-22", "originalTime": "12:19:47.322", "personProfile": null, "provider": null, "rRuleData": {"byMonthDays": null, "byWeekDays": null, "flexibleRecurringPatternType": null, "frequency": null, "intervals": null, "nextTriggerTimes": null, "notificationTimes": null, "recurEndDate": null, "recurEndTime": null, "recurStartDate": null, "recurStartTime": null, "recurrenceRules": null}, "recurrenceEligibility": false, "recurringPattern": null, "remainingTime": 0, "reminderAppLabel": null, "reminderLabel": "Nothing", "reminderSubLabel": null, "skillInfo": null, "snoozedToTime": null, "sound": {"displayName": "Simple Alarm", "folder": null, "id": "system_alerts_melodic_01", "providerId": "ECHO", "sampleUrl": "https://s3.amazonaws.com/deeappservice.prod.notificationtones/system_alerts_melodic_01.mp3"}, "status": "ON", "targetPersonProfiles": null, "timeZoneId": null, "timerLabel": null, "tmwNotificationProperties": null, "triggerTime": 0, "type": "Reminder", "version": "2", "date_time": "2019-10-22 12:19:47.322"}]]
```

**Additional context**

**Comment by alandtse** [comment]
Can you show the lovelace yaml for the card for the sensors?

```yaml
entities:
  - entity: sensor.great_room_next_alarm
  - entity: sensor.great_room_next_reminder
  - entity: sensor.great_room_next_timer
title: Alarms
type: entities
```

In my test system I just did this for all my alarms and they appear to show correctly.

Clicking on each sensor gives:
`2019-10-22 18:59:03.325000-07:00`
`2019-10-22 18:59:00-07:00`
`2019-10-22 18:58:20.872131-07:00`

**Comment by mikeage** [comment]
Sure, the card is:
```
type: entities
entities:
  - entity: sensor.parents_room_next_reminder
  - entity: sensor.parents_room_next_timer
  - entity: sensor.parents_room_next_alarm
title: Alexa Test
```
And right now it's showing me:
<img width="470" alt="Screen Shot 2019-10-23 at 6 03 49" src="https://user-images.githubusercontent.com/87874/67353367-0ff42b80-f55b-11e9-9912-a851f5e4f189.png">
(there are no reminders or timers set; there is an alarm)
