### ISSUE TITLE
Send a message to a user with yellow notification ring

### ISSUE THREAD

**Issue by welbo97** [custom-components/alexa_media_player#450]
When you ask alexa to "Leave a message for XXX", you can record a voice message for a user. The message is delivered to the named user's mobile device and a yellow ring appears on the device. If the user doesn't read the notification on the mobile device, the yellow ring stays on and a request to the device of "What are my notifications?" will play the voice message. 
I would like automations to have the ability to set the yellow ring indicator on the device and possibly store an audio file or even have a TTS/Announce message waiting. 

For instance, when you come home from work, the yellow ring is lit up. You ask, "Alexa, what are my notifications?" and she says, "Your home assistant has an update available". Or maybe, "There have been 97 failed login attempts to your home assistant today".

**Comment by alandtse** [comment]
If you can find out how to do it in the app, you may be able to get information for us to leverage.

**Comment by welbo97** [comment]
Through the app, in the communication section, Message icon, you can choose a contact and send a message. The echo's will all show a yellow ring and make the notification tones. A push notification goes to the user logged in to the account's mobile device. The yellow ring remains unless the user reads the message in their Alexa app or asks alexa "What are my notifications". (This is all ios based for me).

**Comment by welbo97** [comment]
Looks like  ```Alexa.Notifications.SendMobilePush``` will send a message to the routine holder's account but it doesn't create the notification alert like sending a message through the app does. I do not find any other action types that allow the notification ring to light up either. Maybe they will add it to a future version of the app as an action from a routine. I'll keep an eye on it. 
I suppose if/when it is added as a useable action, it will be a simple matter of making the api call from HA through formatted json that calls the service as it is named from sequence discovery? 
(in re-reading that question, it is hard to understand. What I really mean is: "Can HA use any of the sequence:type calls from the notify.alexa_media or media_player.send_command service calls? "

**Comment by alandtse** [comment]
Yes, typically once we can find the sequence you can just [call it.](https://github.com/custom-components/alexa_media_player/wiki#sequence-commands-versions--100)

**Comment by gadgetchnnel** [comment]
I currently do this using an Alexa skill called Notify Me (there now appear to be two skills with this name, the one I use is by Thomptronics). Once this is set up, it gives you a RESTful API you can post messages to which are sent as notifications to your Alexa devices.

I have it set up in my configuration like this:

```
notify:
  - platform: restful
    name: notifyme
    message_param_name: notification
    resource: https://api.notifymyecho.com/v1/NotifyMe
    data:
    accessCode: <access code provided by Notify Me>
  - platform: group
   name: alexa
   services:
    - service: notifyme
    - service: alexa_media_everywhere
      data:
        data:
          type: announce
          method: all
```

This gives me two notify services:

* notify.notifyme - sends notifications to all Alexa devices with the yellow notification ring.
* notify.alexa - will announce the message on all Alexa devices and also send it as a notification, meaning you can still get the notification even if there is nobody around when it goes off.
