### ISSUE TITLE
Play A Specific Amazon Music Track

### ISSUE THREAD

**Issue by codeclinic** [custom-components/alexa_media_player#460]
I'd really like to play a specific track from Amazon Music via my echo devices. The current wiki section gives the Boys II Men example but doesn't state if this just plays a random B2M  song or whether this is a playlist of some sort.

Isit possible to play a specific track? If so, how do we go about doing this, is it done by name orsome component of the QueryString?

I've tried playinga track by name, and by a couple of variables in the QuerString but none of them work. Occassionally (very  rarely) I'll get the echo device asking me which of several tracks I meant. But, that is as  near as it gets for me. Here's my latest attempt:

```
alexa_test:
  sequence:
    - service: media_player.play_media
      data_template:
        entity_id: media_player.lounge
        media_content_id: "A1PA6795UKMFR9"
        media_content_type: "AMAZON_MUSIC"
```
