### ISSUE TITLE
Support TTS Phrases

### ISSUE THREAD

**Issue by embeddeddev** [custom-components/alexa_media_player#573]
**Is your feature request related to a problem? Please describe.**
Idea is to support predefined Alexa phrases as selectable in Automations area of Alexa App

**Describe the solution you'd like**
Support field ``cannedTtsStringId`` for payload of new type ``Alexa.CannedTts.Speak``

**Additional context**
A simple request looks like following.
The field ``cannedTtsStringId`` should be supported by HA YAML configration. Its contents below is just a working sample.
```json
{
  "@type": "com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode",
  "type": "Alexa.CannedTts.Speak",
  "skillId": null,
  "operationPayload": {
    "deviceType": "XXX",
    "customerId": "XXX",
    "cannedTtsStringId": "alexa.cannedtts.speak.curatedtts-category-goodmorning/alexa.cannedtts.speak.curatedtts-random",
    "locale": "XXX",
    "deviceSerialNumber": "XXX"
  },
  "name": null
}
```

**Comment by alandtse** [comment]
Thanks. Same as the other request. HA won't allow this info to be passed through I believe because the `play_media` service doesn't allow additional arguments. If that's changed, please let me know and I'll look into it.

**Comment by gadgetchnnel** [comment]
@alandtse Could you use something like what is used with the [Plex integration](https://www.home-assistant.io/integrations/plex/#service-play_media)?
This takes quote escaped JSON as the media_content_id. Here is one of the example from the documentation:

```
service: media_player.play_media
data:
  entity_id: media_player.plex
  media_content_type: "{ \"library_name\" : \"My Music\", \"artist_name" : \"Adele\", \"album_name\" : \"25\”, \"track_name\" : \"hello\", \"shuffle\": \"0\" }
  media_content_type: MUSIC
```

I could image that something similar could be used, maybe using a JSON object which contains the sequence type and the **operationPayload** (with ALEXA_CURRENT_DEVICE_TYPE for the device type and ALEXA_CURRENT_DSN for the serial number).
