### ISSUE TITLE
Device is not excluded

### ISSUE THREAD

**Issue by pattyland** [custom-components/alexa_media_player#632]
**Describe the bug**
I configured the device "Sören's Alexa App for PC" in the exclude_devices list but it is shown in Home Assistant. I copied ist exactly (including quotes) from https://alexa.amazon.de/api/devices-v2/device

All other devices in this are excluded successfully.

**Expected behavior**
Device is excluded from Home Assistant

**System details**
 - Home-assistant (version): 0.107.7
 - Hassio (Yes/No): yes
 - alexa_media  (version from `const.py` or HA startup): 2.5.11
 - alexapy (version from `pip show alexapy` or HA startup): (I don't know how to get this value)

**Comment by alandtse** [comment]
Quotes should not be copied and there can't be any trailing spaces. Please provide logs for alexa_media on startup for further debugging.

**Comment by pattyland** [comment]
Thanks for your reply. I'm using an IDE, I can confirm that there quotes are correct and they are no trailing spaces. I guess this line is important:

```
2020-04-08 05:57:36 DEBUG (MainThread) [custom_components.alexa_media] m**l@p**********e: Existing: [] New: ['Überall', "Sören's Alexa App for PC", 'Wohnzimmer', 'Sörens Fire TV Stick']; Filtered out by not being in include: [] or in exclude: ["Sören's Reverb.ai", "Sören's echosim_BETA", "Sören's 2nd Reverb.ai", 'Sörens Fire', 'Badezimmer', "Sören's Fire TV", "Sören's 2nd Roav Car Charger", 'Stereoanlage', 'Schlafzimmer', 'Küche', 'This Device', "Sören's Alexa Apps"]
```
I really seems like one entry is ignored in the exclude list.

Other devices in the list like "Sören's echosim_BETA" are excluded as expected. There are no internationalization issue in the UI. 

This may be a very dump question: I started with the config via configuration.yaml and my exclude list is still there. Sometime when this integration got available via HACS I used the integration ui to add my account. I read that the [Entity Registry](https://github.com/custom-components/alexa_media_player/wiki/Configuration#configuring-inclusions-or-exclusions-versions--096) **may** be the preferred mechanism. Should I move?

**Comment by alandtse** [comment]
Can you show me your `configuration.yaml` entry for exclude_devices?

**Comment by pattyland** [comment]
Sure!

```
accounts:
  - email: "***"
    password: "***"
    url: "amazon.de"
    exclude_devices:
    - "Sörens Fire"
    - "Sören's Reverb.ai"
    - "Sören's 2nd Reverb.ai"
    - "Sören's Fire TV"
    - "This Device"
    - "Küche"
    - "Schlafzimmer"
    - "Badezimmer"
    - "Stereoanlage"
    - "Sören's Alexa Apps"
    - "Sören's echosim_BETA"
    - "Sören's 2nd Roav Car Charger"
    - "Sören's Alexa App for PC"
    - "Alexa Apps von Sören"
```
