### ISSUE TITLE
Integration gets duplicated when config entry is renamed (HA 0.109)

### ISSUE THREAD

**Issue by SeanPM5** [custom-components/alexa_media_player#665]
**Describe the bug**
In the upcoming Home Assistant 0.109 release, there is a feature that allows users to rename config entry. This is a handy feature that many will use, to clean up some of the long and ugly default names.

After doing this with Alexa Media Player however, I noticed that it always gets re-added again as a duplicate but with no devices or entities. Pic shared below in screenshot section.

When I asked about this in HA's Discord #beta channel, Frenck quickly identified the issue as being here: https://github.com/custom-components/alexa_media_player/blob/dev/custom_components/alexa_media/__init__.py#L126 and said the following:

"The component matches configs done via YAML based on the entry title. if it cannot find it, it will just create a new config entry. The title contains the email and URL. instead of matching on title, he could have matched against the actual config entry data."

**To Reproduce**
1. Go to "Integrations" page (in Home Assistant 0.109)
2. Click on "Rename" under the Alexa Media Player tile
3. Either change the name, or delete all of the text so it's blank (which is what I did)
4. Now restart, once you restart, you'll get the duplicate as seen in above pic

**Expected behavior**
Allow renaming as normal, without creating duplicate. It can be frustrating if a user renames it and it just always gets added back as a duplicate entry.

**Screenshots**
![image](https://i.imgur.com/6uYaO3b.png)

**System details**
 - Home-assistant (version): 0.109.0b4
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug). Yes
 - alexa_media  (version from `const.py` or HA startup): v2.5.15 thru HACS
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**
My YAML config if needed

```
alexa_media:
  accounts:
    - email: !secret amazon_username
      password: !secret amazon_password
      url: amazon.com
      # Optional
      exclude_devices:
        - "My Dash"
        - "Sean's Ford/Lincoln+Alexa App"
        - "Sean's Alexa Apps"
        - "Sean's 4th Echo Dot"
        - "Sean's Fire TV"
        - "Everywhere"
```
