### ISSUE TITLE
Notification Events

### ISSUE THREAD

**Issue by Ahrak** [custom-components/alexa_media_player#686]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
I checked the docs and the code and didn't find an event that is triggered for notification sensors (alarm/reminder/timer). 

**Describe the solution you'd like**
It would be really helpful to have events if the notifications triggers.
This means that the timestamp state of the notifications sensor matches the current time.
This could be implemented in the `AlexaMediaNotificationSensor`?

event docs:
https://developers.home-assistant.io/docs/dev_101_events/

**Describe alternatives you've considered**
Currently my entry in automations.yaml looks like this:

```yaml
- alias: alexa_forward_reminders
  trigger:
  - platform: template
    value_template: "{{ as_timestamp(states('sensor.echo_wohnzimmer_next_reminder')) == as_timestamp(now())  }}"
  condition: [ ]
  action:
  - service: notify.hass_synchat
    data_template:
      message: 'Alexa Reminder: {{ state_attr(''sensor.echo_wohnzimmer_next_reminder'',''reminder'') }}'
```

**Additional context**
With event it will be something like:
```yaml
- alias: alexa_forward_reminders
   trigger
     platform: event
     event_type: alexa_media_player.notification
     event_data:
      entity_id: sensor.echo_wohnzimmer_next_reminder
   condition: [ ]
   action:
   - service: notify.hass_synchat
      data_template:
        message: 'Alexa Reminder: {{ trigger.event.message }}'
```

This would be a better approch for automatisations based on notifications and provide better posibillities for notification filtering.
