### ISSUE TITLE
Alexa Notify not pausing with full stops or commas anymore

### ISSUE THREAD

**Issue by pdgithub78** [custom-components/alexa_media_player#724]
**Describe the bug**
If you write a message and include a full stop or comma Alexa used to pause at each. Now she ignore's these and just reads the message a one long sentence. I have tried all older versions of the intergration that worked and the result is the same. I would assume it is an Amazon recent change?

**To Reproduce**
Run a notify.alexa_media service with codes such as

data:
  type: tts
message: >-
  Hello, how are you? I am fine. What is the weather like?
target:
  - media_player.lounge_echo

**Expected behavior**
When alexa reads this she should pause where there is a question mark, full stop or comma, but now she doesn't

**Screenshots**
NA

**System details**
 - Home-assistant (version): 0.109.6
 - Hassio (Yes/No): Yes (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup): 2.7.5 but also tried other versions available in HACS
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
No Error logs available

**Additional context**

**Comment by stevenjev** [comment]
It looks like this is a user known issue that isn’t just limited to this project.

Discussed in this [thread](https://www.reddit.com/r/alexa/comments/gkzamb/my_alexa_suddenly_ignores_absolutely_all/?utm_source=share&utm_medium=ios_app&utm_name=iossmf)

**Comment by 3ative** [comment]
I thought it was my setup... Phew. 🤦‍♂️
Let's hope it's fixed soon, some of my TTS's contain "Ok." which she now reads aloud as "Oklahoma" !!! 🤣
LOL

**Comment by grantalewis** [comment]
Same here.

In my case I discovered that the problem only occurs when type is set to tts. It doesn't occur when type is set to announce.

```
  - alias: Bed Time Greeting Test
    initial_state: on
    trigger:
      - platform: state
        entity_id: switch.family_room_piano_lamp
        to: 'on'
    action:
      - service: alexa_media.update_last_called
      - delay: '00:00:03'
      - service: notify.alexa_media
        data_template:
          target: 
            - '{{ states.sensor.last_alexa.state }}' 
          data:
            type: announce
            #type: tts
            #(...code continues...)
```
