### ISSUE TITLE
type: announce not works

### ISSUE THREAD

**Issue by Stefaniscion** [custom-components/alexa_media_player#730]
**Describe the bug**
type: announce not works
(like: https://github.com/custom-components/alexa_media_player/issues/114#issuecomment-472174540)

**Communications for my echo device in Alexa App is Active**

THIS code works:
```
data:
  type: tts
message: test
target:
  - media_player.echo
```

THIS code dosn't:
```
data:
  method: speak
  type: announce
message: test
target:
  - media_player.echo
```
I got no error in log file...

**System details**
 - Home-assistant (version): 0.109.6
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): 2.7.5
