### ISSUE TITLE
Speech Synthesis Markup Language is not working with tts

### ISSUE THREAD

**Issue by schoenof** [custom-components/alexa_media_player#762]
Speech Synthesis Markup Language is not working with tts but works fine with announce....

SSML worked originally with tts when Keaton first posted about it here....but then stopped working in later updates....

THIS READS the XML tags as text - In HA Developer tools -> Services
Service = notify.alexa_media
Service Data
```
message: <amazon:effect name="whispered">test</amazon:effect>
data:
  type: tts
target: media_player.upstairs_echo_dot
```

THIS WORKS - In HA Developer tools -> Services
Service = notify.alexa_media
Service Data
```
message: <amazon:effect name="whispered">test</amazon:effect>
data:
  type: announce
  method: all
target: media_player.upstairs_echo_dot
```
