### ISSUE TITLE
No more tts to echo dot

### ISSUE THREAD

**Issue by antoweb** [custom-components/alexa_media_player#859]
**Describe the bug**
Echo dot no more tts notify

**To Reproduce**
Create an automation with notify.alexa_media like this
```yaml
data:
  method: all
  type: announce
message: C'è qualcuno al portone
target: media_player.echo_dot_di_MISSING
```

No more tts on echo dot

**Expected behavior**

**Screenshots**

**System details**
 - Home-assistant (version): 0.113.1
 - Hassio Yes restartes
This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**
