### ISSUE TITLE
Synchronised Radio Output on Alexa Groups

### ISSUE THREAD

**Issue by MiguelESP89** [custom-components/alexa_media_player#925]
**Describe the bug**
I want to hear my Radio Channel in TuneIn on my Alexa group "Wohnung". in this group is a Alexa Echo 2.Gen and a Alexa Dot 3. Gen. But if i start the script it didn't work

Alexa Echo Dot: media_player.kuche
Alexa Echo 2.Gen : media_player.echo_zimmer

**To Reproduce**
1. I created a script 

The content of the script is

radio_zimmer_1live:
      alias: Radio_Zimmer_1live
      icon: mdi:radio
      mode: single
      sequence:
      - data:
          entity_id: media_player.echo_wohnung. ##Group Wohnung! 
          media_content_id: 1live
          media_content_type: TUNEIN
        entity_id: media_player.wohnung
        service: media_player.play_media

**Expected behavior**
A soundoutput synchonised on all Echos in my group

**Screenshots**
![Bildschirmfoto 2020-09-12 um 13 17 34](https://user-images.githubusercontent.com/39128034/92994422-54354500-f4fa-11ea-82aa-96fd5f039458.png)

**System details**
 - Home-assistant (0.114.4): 
 - Hassio (Yes)

**Comment by alandtse** [comment]
Can you do this in the app? We don't control any syncing. That's up to Amazon.

**Comment by MiguelESP89** [comment]
Yes, with the Alexa App works

**Comment by alandtse** [comment]
Please provide logs of the service call.

**Comment by alandtse** [comment]
Is this an Alexa defined group?

**Comment by Dielee** [comment]
@MiguelESP89 try this: 

```
play_1live_badschlaf:
  alias: 1Live BadSchlaf
  sequence:
  - service: media_player.play_media
    data:
      entity_id: media_player.oneRandomEcho
      media_content_id: eins live auf groupName gruppe
      media_content_type: TUNEIN
```

like this: 
```
play_1live_badschlaf:
  alias: 1Live BadSchlaf
  sequence:
  - service: media_player.play_media
    data:
      entity_id: media_player.wohnzimmer
      media_content_id: eins live auf badschlaf gruppe
      media_content_type: TUNEIN

```
